version: '3.9'

services:
  # DB
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass1234!
    ports:
      - "1433:1433"
    networks:
      - ecommerce-network
    volumes:
      - sql_data:/var/opt/mssql

  # Messaging Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network

  # Stock Microservice
  stock-service:
    build:
      context: .\StockService
      dockerfile: Dockerfile
    container_name: stock-service
    depends_on:
      - sqlserver
      - rabbitmq
    ports:
      - "5001:80"
    networks:
      - ecommerce-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=StockDb;User Id=sa;Password=Pass1234!;TrustServerCertificate=True;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Queue=order-confirmed

  # order Microservice
  order-service:
    build:
      context: .\orderService
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - sqlserver
      - rabbitmq
    ports:
      - "5002:80"
    networks:
      - ecommerce-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=orderDb;User Id=sa;Password=Pass1234!;TrustServerCertificate=True;

  # API Gateway
  api-gateway:
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - stock-service
      - order-service
    ports:
      - "5000:80"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:

volumes:
  sql_data:
