version: '3.9'

services:
  # DB
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pass123
    ports:
      - "1433:1433"
    networks:
      - ecommerce-network
    volumes:
      - sql_data:/var/opt/mssql

  # Messaging Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network

  # Stock Microservice
  stock-service:
    build:
      context: ../../src/Services/StockService
      dockerfile: Dockerfile
    container_name: stock-service
    depends_on:
      - sqlserver
      - rabbitmq
    ports:
      - "5001:80"
    networks:
      - ecommerce-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=StockDb;User Id=sa;Password=pass123;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Queue=sales-confirmed

  # Sales Microservice
  sales-service:
    build:
      context: ../../src/Services/SalesService
      dockerfile: Dockerfile
    container_name: sales-service
    depends_on:
      - sqlserver
      - rabbitmq
    ports:
      - "5002:80"
    networks:
      - ecommerce-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SalesDb;User Id=sa;Password=pass123;

  # API Gateway
  api-gateway:
    build:
      context: ../../src/APIGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - stock-service
      - sales-service
    ports:
      - "5000:80"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:

volumes:
  sql_data:
